# Generated by Django 3.0.7 on 2021-01-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_api', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=512)),
                ('abstract', models.TextField()),
                ('slug_name', models.CharField(max_length=128)),
                ('published_date', models.DateTimeField()),
                ('url', models.TextField()),
                ('internal_source', models.CharField(max_length=128)),
                ('media_copyright', models.CharField(max_length=256)),
            ],
        ),
    ]
